version: '3.8'


services:

  mongo_db:
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27017:27017"
    networks:
      - custom

  redis:
    container_name: cache
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
      
networks:
  custom:
    driver: bridge