version: '3.8'

volumes:
  redis-data:
  mongo-data:

services:
  redis:
    container_name: cache_dev
    image: redis:latest
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/var/redis/data
    ports:
      - 6379:6379 
  mongo_db:
    image: mongo
    restart: always
    container_name: mongo_db
    ports: 
      - 27015:27015
    volumes:
      - mongo-data:/data/db
  backend:
    depends_on:
      - redis
      - mongo_db
    container_name: backend
    build: ../app
    env_file: ../.env
    restart: always
  nginx:
    container_name: web
    build: ./nginx
    depends_on:
      - backend
    ports:
      - 8000:80
    